Add new rule "require-valid-svg"
ember-template-lint/ember-template-lint pull request #1524
Opened 2020-09-18 13:23 UTC by KamiKillertO

This is an integration for the rule described in #1507

2020-11-24 15:07 UTC, MelSumner commented on test/unit/rules/require-valid-svg-test.js
> +        message: 'An `<svg>` element with role `image` should have a none empty alternative text',
```suggestion
        message: 'An `<svg>` element with role `image` should have valid alternative text',
```

2020-11-24 15:07 UTC, MelSumner commented on test/unit/rules/require-valid-svg-test.js
> +        message: 'An `<svg>` element with role `image` should have a none empty alternative text',
```suggestion
        message: 'An `<svg>` element with role `image` should have valid alternative text',
```

2020-11-24 15:07 UTC, MelSumner commented on test/unit/rules/require-valid-svg-test.js
> +          'An `<svg>` element with role `image` should contains contain a none empty `<title>` element',
```suggestion
          'An `<svg>` element with role `image` should contains contain a valid `<title>` element',
```

2020-11-24 15:08 UTC, MelSumner commented on test/unit/rules/require-valid-svg-test.js
> +          'An `<svg>` element with role `image` should contains contain a none empty `<title>` element',
```suggestion
          'An `<svg>` element with role `image` should contains contain a valid `<title>` element',
```

2020-11-24 15:08 UTC, MelSumner commented on test/unit/rules/require-valid-svg-test.js
> +        message: 'An `<svg>` element with role `image` should have a none empty alternative text',
```suggestion
        message: 'An `<svg>` element with role `image` should have valid alternative text',
```

2020-11-24 15:09 UTC, MelSumner commented on test/unit/rules/require-valid-svg-test.js
> +          'An `<svg>` element without role `image` should not have the `alt` attribute defined',
```suggestion
          'An `<svg>` element without `role="image"` should not have the `alt` attribute defined',
```

2020-11-24 15:09 UTC, MelSumner commented on test/unit/rules/require-valid-svg-test.js
> +          'Parent tag of an `<svg>` element should have an none empty `aria-label` attribute',
```suggestion
          'Parent tag of an `<svg>` element should have a valid `aria-label` attribute',
```

2020-11-24 15:10 UTC, MelSumner commented on docs/rule/require-valid-svg.md
> +> All non-text content that is presented to the user has a text alternative that serves the equivalent purpose, with few exceptions. See: [WCAG 1.1.1 - Non-text Content](https://www.w3.org/TR/WCAG21/
```suggestion
- All non-text content that is presented to the user has a text alternative that serves the equivalent purpose, with few exceptions. See: [WCAG 1.1.1 - Non-text Content](https://www.w3.org/TR/WCAG21/#non-text-content)
```

2020-11-24 15:10 UTC, MelSumner requested changes
Please also add this new rule to the `a11y.js` config file. Thank you!

2020-11-24 16:05 UTC, KamiKillertO commented
Thanks, @MelSumner for the review, but do you think we should keep this rule or as mentioned in this [comment](https://github.com/ember-template-lint/ember-template-lint/issues/1507#issuecomment-702603780) split the rule into multiples rules.

2020-12-17 19:45 UTC, lifeart commented on lib/rules/require-valid-svg.js
> +                'An `<svg>` element inside a `<a>` or `<button>` element should have the `aria-hidden` attribute set to true',
wondering, could we add fixer for it?

2021-04-15 13:11 UTC, closed without merging