Add additional elements to `no-obsolete-elements` rule elements list
ember-template-lint/ember-template-lint pull request #1532
Opened 2020-09-24 02:08 UTC by bmish

A few more from: https://www.w3docs.com/learn-html/deprecated-html-tags.html

2020-09-24 02:40 UTC, MelSumner requested changes
So that website is well-known for having incorrect information. If you can find references in the spec that indicate that these elements are deprecated, please add the spec reference URL in the doc and ask me to re-review. 

Thank you!

2020-09-24 14:03 UTC, bmish commented
@MelSumner good point, I updated to only add two additional elements `s` and `u` that we were missing from the official w3 site: https://dev.w3.org/html5/pf-summary/obsolete.html

2020-09-24 14:35 UTC, rwjblue commented
@bmish can you update to target `next` branch?

2020-09-28 19:01 UTC, rwjblue approved these changes

2020-09-28 22:41 UTC, MelSumner approved these changes

2020-09-28 22:44 UTC, merged