Make builtin-component-arguments work for Textarea too
ember-template-lint/ember-template-lint pull request #2013
Opened 2021-06-25 20:25 UTC by lifeart

resolves https://github.com/ember-template-lint/ember-template-lint/issues/1920

2021-08-30 22:09 UTC, rwjblue requested changes

2021-08-30 22:09 UTC, rwjblue commented on docs/rule/builtin-component-arguments.md
> +of the lower-case `textarea` HTML element. These arguments should be set via e.g.
I know this is pedantic, but `value` is **not** a valid attribute of `<textarea></textarea>`. It is however a valid **property** of the resulting DOM element. 😭 

```suggestion
The builtin `Textarea` component has several arguments that match properties
of the lower-case `textarea` HTML element. These arguments should be set via e.g.
```

2021-09-28 18:48 UTC, MelSumner commented on docs/rule/builtin-component-arguments.md
> +the `Input`, `Textarea` components, but might be extended in the future to also warn about
```suggestion
the `Input`, and one property on the `Textarea` components, but might be extended in the future to also warn about
```

2021-09-28 18:49 UTC, MelSumner requested changes
One small suggested edit to the docs change, otherwise looks good to me! 👍 @rwjblue looks like it's ready to re-review.

2021-10-04 15:08 UTC, merged

2021-10-04 15:08 UTC, bmish approved these changes