Add `requireActionHelper` config option to `no-element-event-actions`
ember-template-lint/ember-template-lint pull request #2269
Opened 2021-12-06 15:04 UTC by jamescdavis

Fixes #1343

This adds a `requireActionHelper` config option to the `no-element-event-actions` rule, which is `true` by default.. When this option is enabled, this rule will apply, only when the `{{action}}` helper is present.

By default, when `no-element-event-actions` is enabled, this fails linting:

```hbs
<button type="button" onclick={{action this.myAction}}>Go!</button>
```

But this does not error:

```hbs
<button type="button" onclick={{this.myAction}}>Go!</button>
```

Setting `requireActionHelper` for `no-element-event-actions` to `false` will cause _both_ of these to error.

2021-12-06 15:07 UTC, jamescdavis commented
@mehulkar @rwjblue @MelSumner @Turbo87 @GiDeBus

2021-12-06 15:10 UTC, jamescdavis commented
I'd love for this option to be enabled by default, but that's a breaking change. Maybe in the next major. 🙂

2021-12-06 16:29 UTC, bmish requested changes
There's an upcoming major v4 release (https://github.com/ember-template-lint/ember-template-lint/issues/1908) that we could change the default value of this option in.

However, note that this rule is not in the `recommended` config. It was replaced as a recommended rule by [no-action](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-action.md) as mentioned in https://github.com/ember-template-lint/ember-template-lint/pull/858.

2021-12-06 16:55 UTC, jamescdavis commented on docs/rule/no-element-event-actions.md
> +  * `actionHelperOptional` -- Apply this rule even when the {{action}} helper is not present
That was my first version, but then I convinced myself that was confusing. But now it seems better again 😆

2021-12-06 16:58 UTC, jamescdavis commented
@bmish maybe it could be added to the recommended config (with `requireActionHelper` defaulting to `false`) for v4?

2021-12-06 17:11 UTC, bmish commented
> @bmish maybe it could be added to the recommended config (with `requireActionHelper` defaulting to `false`) for v4?

We could probably do that. `no-element-event-actions` was previously totally overlapping/redundant given the `no-action` rule, but now it would cover this additional scenario.

On the other hand, there's a completely different way we could approach this. What if we added a `includeDynamicEventProperties` option to the `no-action` rule that would cover this new behavior? That way, we could let the recommended `no-action` rule handle everything, instead of needing two partially-redundant/overlapping recommended rules.

I'm not sure which approach I prefer yet.

2021-12-06 18:38 UTC, jamescdavis commented
@bmish I went ahead and made the changes you suggested. If we decided to do it in `no-action` instead, I can tackle that.

I also made a little improvement to the test harness that greatly aided setting up message matchers for the config error cases: #2270

2021-12-07 17:12 UTC, bmish approved these changes
@jamescdavis here's what I would like to do:

1. I'll merge this change and we can disable `requireActionHelper` on `no-element-event-actions` in the next major release to make this rule more strict. That improves the situation for anyone using this rule. This will continue to not be a recommended rule and honestly we could deprecate or delete this rule at some point given how `no-action` handles it already.
2. Additionally, let's also add `includeDynamicEventProperties` to `no-action` (default false), and we will set that option default to true in the next major release. `no-action` will be the only `recommended` rule and will handle everything this way, without having any redundant/overlapping recommended rules.

So if you want to work on 2 it would be much appreciated. Thanks for your work!

2021-12-07 17:13 UTC, merged