Add autofixer to `attribute-indentation` rule
ember-template-lint/ember-template-lint pull request #2271
Opened 2021-12-09 21:43 UTC by VincentMolinie

The code is not clean at all but it's a beginning. Any help is welcome on the cleaning part 🙏

2022-01-06 17:33 UTC, bmish commented on test/unit/rules/attribute-indentation-test.js
> +  ].filter((index) => index < 0),
remove...

2022-01-10 13:20 UTC, VincentMolinie commented
@bmish I think it's good 🤩

2022-01-10 13:43 UTC, bmish requested changes
* Looks like linting needs to be fixed
* I see some commented-out code
* I think we still need some more comments throughout complex parts of the logic / flow to ensure readers understand what's happening

2022-01-10 13:43 UTC, bmish commented on lib/rules/attribute-indentation.js
> +    // throw new Error();
commented

2022-01-10 13:43 UTC, bmish commented on lib/rules/attribute-indentation.js
> +    let index = node.program.loc.start.line - 1;
Can you add a comment to explain what this block is doing?

2022-01-10 13:43 UTC, bmish commented on lib/rules/attribute-indentation.js
> +        // fixedNode = this.sourceEdited ? this.fixLine(this.sourceEdited.split('\n'), fixedNode.loc.start, fixedNode.loc.start, path) : fixedNode;
commented?

2022-01-10 13:43 UTC, bmish commented on lib/rules/attribute-indentation.js
> +  iterateChildren(node, parentPath, childrenPath) {
Can you add jsdoc comment to explain what this function is doing?

2022-01-10 13:43 UTC, bmish commented on test/unit/rules/attribute-indentation-test.js
> +    // {
Commented?

2022-01-11 14:55 UTC, VincentMolinie commented
Back to you @bmish. Thanks for your review. FOr the test to pass I need the PR on ember-template-recast 🙏

2022-01-12 18:24 UTC, VincentMolinie commented
Actually @bmish the tests are passing on local it only crash in the CI 🤔. No idea why. Any idea ?

2022-01-15 11:33 UTC, VincentMolinie commented
@bmish should be all god now 😉

2022-01-15 16:12 UTC, bmish commented
Can you fix CI?

2022-01-15 16:17 UTC, bmish commented
Can you also make sure that all of the lines of code in this rule are covered by the tests? I just checked and see many lines missing coverage:

```
attribute-indentation.js                       |   95.19 |    90.55 |     100 |   95.16 | ...2,764,771,777,785,792-808 
```

```
yarn test:jest test/unit/rules/attribute-indentation-test.js
```

2022-01-21 15:32 UTC, bmish requested changes
Coverage looks better but I still see the following uncovered lines:

```
yarn test:jest test/unit/rules/attribute-indentation-test.js
```

```
File                                             | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s            
-------------------------------------------------|---------|----------|---------|---------|------------------------------
  attribute-indentation.js                       |   98.42 |    93.56 |     100 |   98.41 | 544-546,757,797  
```

The code for this rule is quite long and complicated so it's even more important that we ensure all of its lines are covered by comprehensive tests. 

Thanks for your work on this so far! Nearing the finish line.

2022-01-24 09:38 UTC, VincentMolinie commented
> Coverage looks better but I still see the following uncovered lines:
> 
> ```
> yarn test:jest test/unit/rules/attribute-indentation-test.js
> ```
> 
> ```
> File                                             | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s            
> -------------------------------------------------|---------|----------|---------|---------|------------------------------
>   attribute-indentation.js                       |   98.42 |    93.56 |     100 |   98.41 | 544-546,757,797  
> ```
> 
> The code for this rule is quite long and complicated so it's even more important that we ensure all of its lines are covered by comprehensive tests.
> 
> Thanks for your work on this so far! Nearing the finish line.

- 544-546: I did not touch those line. I don't really know how you get there and why ?
- 757: I tried to add a test but it never pass inside. It correspond to have `config: false`
- 797: Same thing as the previous one I tried to add `config: undefined` but it never pass that line 😞

2022-01-24 15:22 UTC, bmish commented
@VincentMolinie thanks for the explanation. Those may be pre-existing issues then or even deadcode. So we can ignore that then.

The next step is to run this autofixer on a real codebase. I tried running on a large codebase and I'm hitting various crashes.

```hbs
{{#sq-dropdown as |dropdown|}}

  {{#dropdown.trigger class="button super-table__plus-button"}}
    <i class="{{if isActive "icon-plus-small-hover" "icon-plus-small"}} super-table__plus-button__icon"></i>
  {{/dropdown.trigger}}

{{/sq-dropdown}}

{{directory/onboard-tooltip buttonText=(t "button.ok")
                            content=(t "foo")
                            flag=onboardTooltipFlag
                            flagPrevious=onboardTooltipFlagPrevious
                            popoverClass="foo"}}
```

```
lib/rules/attribute-indentation.js:94
    nodeToReturn._globalNode = path && globalNode;
                             ^
TypeError: Cannot set properties of undefined (setting '_globalNode')
    at AttributeIndentation.fixLine
```

And there appear to be many other crashes. Can you give this a try? Excited for the autofixer but it would be a shame if everyone hits crashes when they try to use it.

2022-02-01 14:35 UTC, VincentMolinie commented
Hey @bmish I don't have time lately to handle those crash sorry. I'll try asap

2025-05-03 17:49 UTC, lifeart commented
closing to move to umbrella ticket related to indentation problems https://github.com/ember-template-lint/ember-template-lint/issues/3209 (feel free to ping me if you have time to work on it)

2025-05-03 17:49 UTC, closed without merging