Add new rule `scope`
ember-template-lint/ember-template-lint pull request #2413
Opened 2022-03-07 20:22 UTC by judithhinlung

This PR adds the new rule `scope` which fixes #2412 .
 
### Background
The scope attribute is used on `<th>` elements to clarify the relationship between a table's header cells and data cells for screen readers. Because placing this attribute on other HTML elements has no effect, only `<th>` elements should declare a value for scope.

This new rule enforces that the scope attribute is only used on `<th>` elements.  

References: 
- [H63: Using the scope attribute to associate header cells and data cells in data tables](https://www.w3.org/TR/WCAG20-TECHS/H63.html)
- [Tables Concepts](https://www.w3.org/WAI/tutorials/tables/)

 **Allowed**:
 
 ```
# examples
<th scope="row">some header cell</th>
<CustomHeader scope={{foo}} />
```

**Forbidden**:

```
# examples
<a scope="col"></a>
<table scope="rowgroup"></table>
```

### Testing
WIP

2022-03-07 20:31 UTC, scalvert commented
Hey @judithhinlung, I know this is still in progress, but can we rename the rule to something a bit less general? Maybe something like `require-valid-scope` or something?

2022-03-08 02:03 UTC, bmish requested changes

2022-03-08 02:03 UTC, bmish commented on test/unit/rules/no-scope-outside-table-headings-test.js
> +  ],
Can we add these to `good`:
* `{{foo-component scope="row"}}`
* `<CustomComponent scope="row" />`

2022-03-08 02:03 UTC, bmish commented on test/unit/rules/no-scope-outside-table-headings-test.js
> +  bad: [
Can we add this to bad just to show that we don't care what the value is?
* `<td scope>`

2022-03-08 19:14 UTC, bmish approved these changes

2022-03-08 19:14 UTC, bmish commented on docs/rule/no-scope-outside-table-headings.md
> +## References
Can you also link to something specific about `scope`? https://www.w3schools.com/tags/att_th_scope.asp

2022-03-08 19:15 UTC, bmish commented on docs/rule/no-scope-outside-table-headings.md
> +## References
Can you also link to 

* https://www.w3.org/TR/WCAG20-TECHS/H63.html
* And the corresponding React lint rule

2022-03-08 19:16 UTC, bmish commented on docs/rule/no-scope-outside-table-headings.md
> +## References
Can you also link to 

* https://www.w3.org/TR/WCAG20-TECHS/H63.html
* And the JSXs A11y [scope rule](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/scope.md).

2022-03-30 20:41 UTC, judithhinlung commented
Hi @bmish, is it okay to merge this pr?

2022-03-30 20:42 UTC, merged