Adds new rule `require-media-caption`
ember-template-lint/ember-template-lint pull request #2497
Opened 2022-05-02 23:13 UTC by judithhinlung

This PR adds the new rule require-media-caption which fixes #2496.

### background
Captions are essential for users who are deaf, as well as those for whom the media content is unavailable, to access synchronized media content. By providing a transcript of the spoken content as well as descriptions of other relevant non-speech information, captions allow users access to the information conveyed via the audio track.

Reference: - [Understanding Success Criterion 1.2.2: Captions (Prerecorded)](https://www.w3.org/WAI/WCAG21/Understanding/captions-prerecorded.html)

**Allowed**:
```
# examples
<audio><track kind="captions" /></audio>
<video muted="true"></video>
<video muted></video>

**Forbidden**:
```
# examples
<audio></audio>
<video><track /></video>
<video><track kind="descriptions" /></video>
<audio muted="false"></audio>
```

### Testing
Test Suites: 137 passed, 137 total
Tests:       5 skipped, 7534 passed, 7539 total
Snapshots:   985 passed, 985 total
Time:        109.104 s
Ran all test suites.
✨  Done in 115.11s.

2022-05-03 20:48 UTC, bmish requested changes
Do you think this rule is suitable to become a `recommended` rule in the next major release?

2022-05-03 20:48 UTC, bmish commented on test/unit/rules/require-media-caption-test.js
> +      template: '<audio muted="false"></audio>',
Shouldn't we test with `muted=false` too?

2022-05-03 20:48 UTC, bmish commented on test/unit/rules/require-media-caption-test.js
> +      result: {
Let's use `verifyResults` snapshot testing for all these test cases.

2022-05-03 23:41 UTC, judithhinlung commented
Thanks for the review @bmish , I have updated the tests to use verifyResults and added a test case validating muted=false fails as expected.

2022-05-03 23:46 UTC, judithhinlung commented
> Do you think this rule is suitable to become a `recommended` rule in the next major release?

Yes I agree that this would be a good `recommended` rule.

2022-05-04 12:39 UTC, bmish commented on docs/rule/require-media-caption.md
> +
I think we can remove this example. We don't really need to show different syntaxes for the same thing.
```suggestion
```

2022-05-04 12:39 UTC, bmish commented on docs/rule/require-media-caption.md
> +This rule **allows** the following:
Can we also show a `video` properly using captions?

2022-05-06 18:27 UTC, bmish approved these changes
Thanks!

2022-05-10 16:47 UTC, merged