`img` tags should not have `role` attribute
ember-template-lint/ember-template-lint pull request #2828
Opened 2023-03-01 16:02 UTC by yannbertrand

Affects `require-valid-alt-text`.

`role` should never be needed when using an `img` tag according to the [W3C Nu Validator](https://validator.w3.org/nu/#textarea).

Closes #2190 and #2579.

2023-03-02 18:57 UTC, MelSumner requested changes
Let's make this rule optional instead of removing it; it's weird but also the only way we can currently identify developer intent. It's also on the topic list for the next ARIA face to face.

2023-03-03 10:17 UTC, yannbertrand commented
> Let's make this rule optional instead of removing it; it's weird but also the only way we can currently identify developer intent.

Thanks for the review. What do you mean by making the rule optional?

Should I remove [these lines](https://github.com/ember-template-lint/ember-template-lint/pull/2828/files#diff-036baf1a0cc3501594ec83f25c8ff5e0b2f981203127e56adadb5adaed1b7427R57-R62)?

> It's also on the topic list for the next ARIA face to face.

Interesting! Is there a planning of these events we can find somewhere?

2023-03-07 11:19 UTC, yannbertrand commented
I've added a commit to accept `role` attributes on `img` tags but do not apply any validation on them, rather than denying them.

2023-06-20 19:16 UTC, jaswilli commented
I think the intended changes here have become more urgent with the recent [aria-query](https://github.com/A11yance/aria-query) updates. Now _both_ versions of an `<img>` with an empty alt tag are error conditions:

empty alt with presentation role:
```bash
$ echo '<img src="src" alt="" role="presentation">' | npx ember-template-lint --
undefined
  1:0  error  Use of redundant or invalid role: presentation on <img> detected.  no-redundant-role
```

empty alt without role:
```bash
$ echo '<img src="src" alt="">' | npx ember-template-lint --
undefined
  1:0  error  If the `alt` attribute is present and the value is an empty string, `role="presentation"` or `role="none"` must be present  require-valid-alt-text
```

2023-08-09 20:32 UTC, HeroicEric commented on test/unit/rules/require-valid-alt-text-test.js
> +    '<img alt="a stylized graphic of a female hamster" role="presentation" src="zoey.jpg">',
`role="presentation"` and `role="none"` are not valid when `alt` is a non-empty string

2023-08-09 20:44 UTC, HeroicEric commented on lib/rules/require-valid-alt-text.js
> -          }
I don't think this should be removed. It is not valid to have a non-empty alt attribute if `role="presentation"` or `role="none"`

2023-08-11 12:01 UTC, yannbertrand commented
I'm closing this in favor of #2954

2023-08-11 12:01 UTC, closed without merging